[package]
name = "blog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark="0.8"
askama = "0.10"
chrono = "*"
katex = "0.4"
regex = "1"
